question_list = [
    {
        'source': 'AP Macroeconomics 2019 MCQ-1',
        'description': 'An economy is operating at a point inside its production possibilities curve (PPC). Which of the following will most likely cause the economy to move toward the current PPC in the short run?',
        'options': [
            'A decrease in government spending',
            'A decrease in inflation',
            'An increase in human capital',
            'An increase in employment',
            'An increase in imports',
        ],
        'answer': 'D',
    },
    {
        'source': 'AP Macroeconomics 2019 MCQ-2',
        'description': 'An increase in which of the following will most likely promote economic growth?',
        'options': [
            'Taxes on investment',
            'The price level',
            'Human capital',
            'Consumption of nondurable goods',
            'Interest rates',
        ],
        'answer': 'C',
    },
    {
        'source': 'AP Macroeconomics 2019 MCQ-3',
        'description': 'Which of the following will cause aggregate supply to increase in Country X?',
        'options': [
            'An increase in personal income taxes',
            'The discovery of low-cost alternative sources of energy',
            'A decrease in labor productivity with no change in nominal wages',
            'Depreciation of country X\'s currency on the foreign exchange market',
            'An increase in the price level',
        ],
        'answer': 'B',
    },
    {
        'source': 'AP Macroeconomics 2019 MCQ-5',
        'description': 'An increase in the price of oil, an important input to production, will result in which of the following in the short run?',
        'options': [
            'A decrease in the price level',
            'A decrease in short-run aggregate supply',
            'A decrease in unemployment',
            'An increase in real wages',
            'An increase in aggregate demand',
        ],
        'answer': 'B',
    },
    {
        'source': 'AP Macroeconomics 2019 MCQ-6',
        'description': 'An economy is currently operating at the full-employment level of output. Which of the following would result in a recessionary gap in the short run?',
        'options': [
            'An increase in the costs of production',
            'An improvement in the productivity of labor',
            'An increase in money supply',
            'A positive supply shock',
            'A decrease in income tax rates',
        ],
        'answer': 'A',
    },
    {
        'source': 'AP Macroeconomics 2019 MCQ-7',
        'description': 'Thailand and Malaysia are trading partners. If the price level in Thailand decreases relative to the price level in Malaysia, what will happen to Thailand\'s exports to Malaysia and Thailand\'s aggregate demand?',
        'options': [
            'Increase; Decrease',
            'Increase; Increase',
            'Increase; Indeterminate',
            'Decrease; Decrease',
            'Decrease; Increase',
        ],
        'answer': 'B',
    },
    {
        'source': 'AP Macroeconomics 2019 MCQ-9',
        'description': 'Which of the following is a fiscal policy action aimed at reducing unemployment?',
        'options': [
            'Decreasing government expenditures',
            'Decreasing income taxes',
            'Decreasing tax credits',
            'Increasing nominal interest rates',
            'Increasing required reserves',
        ],
        'answer': 'B',
    },
    {
        'source': 'AP Macroeconomics 2019 MCQ-10',
        'description': 'Increases in human capital can be achieved by which of the following?',
        'options': [
            'Building more factories',
            'Reducing immigration of skilled workers',
            'Improving the quality of job-training programs',
            'Increasing the physical capital per worker',
            'Increasing government spending on infrastructure',
        ],
        'answer': 'C',
    },
    {
        'source': 'AP Macroeconomics 2019 MCQ-11',
        'description': 'If the marginal propensity to save is 0.25, a \$15 billion increase in government spending will lead to an increase in national income by a maximum of',
        'options': [
            '$60 billion',
            '$45 billion',
            '$15 billion',
            '$11.25 billion',
            '$3.75 billion',
        ],
        'answer': 'A',
    },
    {
        'source': 'AP Macroeconomics 2019 MCQ-13',
        'description': 'The term "value added" for a firm is best defined as which of the following?',
        'options': [
            'The firm\'s sales',
            'The firm\'s sales minus depreciation',
            'The firm\'s sales minus its losses',
            'The firm\'s sales minus the cost of inputs purchased from other firms',
            'The firm\'s profits from its sales',
        ],
        'answer': 'D',
    },
]
